teknofest/Controllers/CartController.cs
using Business.Abstract;
using Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Data;
using teknofest.Identity;
using teknofest.Models;

namespace teknofest.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
        private ICartService _cartService;

        private IOrderService _orderService;

        private UserManager<User> _userManager;
        public CartController(IOrderService orderService, ICartService cartService, UserManager<User> userManager)
        {
            _cartService = cartService;
            _userManager = userManager;
            _orderService = orderService;
        }
        public IActionResult Index()
        {
            var cart = _cartService.GetCartByUserId(_userManager.GetUserId(User));

            return View(new CartModel()
            {
                CartId = cart.Id,
                CartItems = cart.CartItems.Select(i => new CartItemModel()
                {
                    CartItemId = i.Id,
                    FoodId = i.Food.Id,
                    Name = i.Food.Name,
                    Price = i.Food.Price,
                    ImageUrl = i.Food.imageUrl,
                    Quantity = i.Quantity

                }).ToList()
            });
        }
        [HttpPost]
        public IActionResult AddToCart(int foodid, int quantity)
        {
            _cartService.AddToCart(_userManager.GetUserId(User), foodid, quantity);

            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult DeleteFromCart(int foodid)
        {
            _cartService.DeleteFromCart(_userManager.GetUserId(User), foodid);

            return RedirectToAction("Index");
        }
        public IActionResult Checkout()
        {
            var cart = _cartService.GetCartByUserId(_userManager.GetUserId(User));

            var orderModel = new OrderModel();

            orderModel.CartModel = new CartModel()
            {
                CartId = cart.Id,
                CartItems = cart.CartItems.Select(i => new CartItemModel()
                {
                    CartItemId = i.Id,
                    FoodId = i.FoodId,
                    Name = i.Food.Name,
                    Price = i.Food.Price,
                    ImageUrl = i.Food.imageUrl,
                    Quantity = i.Quantity

                }).ToList()
            };

            return View(orderModel);
        }
        [HttpPost]
        public IActionResult Checkout(OrderModel model)
        {
            if (ModelState.IsValid)
            {
                var userId = _userManager.GetUserId(User);
                var cart = _cartService.GetCartByUserId(userId);

                model.CartModel = new CartModel()
                {
                    CartId = cart.Id,
                    CartItems = cart.CartItems.Select(i => new CartItemModel()
                    {
                        CartItemId = i.Id,
                        FoodId = i.FoodId,
                        Name = i.Food.Name,
                        Price = i.Food.Price,
                        ImageUrl = i.Food.imageUrl,
                        Quantity = i.Quantity
                    }).ToList()
                };

                

                SaveOrder(model, userId);
                ClearCart(model.CartModel.CartId);
                return View("Succes");
                
               
            }


            return View(model);
        }

        private void ClearCart(int cartId)
        {
            _cartService.ClearCart(cartId);
        }

        private void SaveOrder(OrderModel model, string userId)
        {
            var order = new Order();

            order.OrderNumber = new Random().Next(111111, 999999).ToString();
            order.OrderState = EnumOrderState.tamamlandı;
            order.PaymentType = EnumPaymentType.CreditCard;


            order.OrderDate = new DateTime();
            order.FirstName = model.FirstName;
            order.LastName = model.LastName;
            order.UserId = userId;
            
            order.Telefon = model.Telefon;
           

            order.OrderItems = new List<OrderItem>();

            foreach (var item in model.CartModel.CartItems)
            {
                var orderItem = new OrderItem()
                {
                    Price = item.Price,
                    Quantity = item.Quantity,
                    FoodId = item.FoodId
                };
                order.OrderItems.Add(orderItem);
            }
            _orderService.Create(order);
        }


        public IActionResult GetOrders()
        {
            var userId = _userManager.GetUserId(User);
            var orders = _orderService.GetOrders(userId);

            var orderListModel = new List<OrderListModel>();
            OrderListModel orderModel;
            foreach (var order in orders)
            {
                orderModel = new OrderListModel();

                orderModel.OrderId = order.Id;
                orderModel.OrderNumber = order.OrderNumber;
                orderModel.OrderDate = order.OrderDate;
                orderModel.Telefon = order.Telefon;
                orderModel.FirstName = order.FirstName;
                orderModel.LastName = order.LastName;
                
                orderModel.OrderState = order.OrderState;
                orderModel.PaymentType = order.PaymentType;

                orderModel.OrderItems = order.OrderItems.Select(i => new OrderItemModel()
                {
                    OrderItemId = i.Id,
                    Name = i.Food.Name,
                    Price = i.Price,
                    Quantity = i.Quantity,
                    ImageUrl = i.Food.imageUrl
                }).ToList();

                orderListModel.Add(orderModel);
            }


            return View("Orders", orderListModel);
        }

    }
}

teknofest/Controllers/MenuController.cs
using DataAccess.Abstract;
using Microsoft.AspNetCore.Mvc;
using teknofest.Models;

namespace teknofest.Controllers
{
    public class MenuController : Controller
    {
        private IFoodCategoryDal _service;
        public MenuController(IFoodCategoryDal service)
        {
            _service = service;
        }
        public IActionResult List()
        {
            var foodCategories = new FoodCategoryList()
            {

                FoodCategories = _service.GetAll()



            };
            return View(foodCategories);
        }

        public IActionResult YemekMenu()
        {
            return View(_service.getYemekMenu());
        }
        public IActionResult IcecekMenu()
        {
            return View(_service.GetAll(i=> i.Url.Contains("icecek")));
        }
        

        public IActionResult Details(string url)
        {
            return View(_service.GetFoodsTheCategory(url));
        }
    }
}

teknofest/Controllers/navbarController.cs
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using teknofest.Identity;
using teknofest.Models;

namespace teknofest.Controllers
{
    public class navbarController : Controller
    {
        //ApplicationContext cnt = new ApplicationContext();
        /*
        public IActionResult Index()
        {
            var degerler = cnt.HakkimizdaSinifis.ToList();
            return View(degerler);
        }
        */
        public IActionResult ChangeLanguage(string culture)
        {
            Response.Cookies.Append(CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
                new CookieOptions() { Expires = DateTimeOffset.UtcNow.AddYears(1) });
            return Redirect(Request.Headers["Referer"].ToString());
        }
    }
}

teknofest/Views/Shared/_FoodCategoryView.cshtml
@model FoodCategory

<div class="card mb-2">
    <img class="card-img-top" src="~/img/@Model.imageUrl" alt="">
    <div class="card-body">
        <h5 class="card-title">@Model.Name</h5>
        <span>@Model.Description</span>
    </div>
    <div class="card-footer text-center">
        <a asp-controller="Menu" asp-action="Details" asp-route-url="@Model.Url" class="btn btn-primary btn-sm">Menüyü İncele</a>


    </div>
</div>   

teknofest/Views/Shared/_FoodView.cshtml
@model Food
@inject LanguageService language

@section CssFurkan{

    <link rel="stylesheet" href="~/css/anaYemekler.css">
    <link rel="stylesheet" href="~/css/mainPage.css">

}

<div class="food">
    <div class="details">
        <div class="img">
            <img src="~/img/@Model.imageUrl" alt="">
        </div>
        <div class="details-sub">
            <div class="food-name">
                <h5>@Model.Name</h5>
            </div>
            <div class="food-price">
                <h5>@Model.Price</h5>
            </div>
            <div class="add-basket">
                    <form method="post" asp-action="AddToCart" asp-controller="Cart" style="display:inline">
                        <input type="hidden" name="foodid" value="@Model.Id" />
                        <input type="hidden" name="quantity" value="1" />
                    <button type="submit" class="btn btn-primary btn-sm">@language.GetKey("sepetEkle")</button>
                    </form>
            </div>
        </div>

    </div>
</div>

teknofest/Views/Shared/_Front.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Anasayfa</title>
    <link rel="stylesheet" href="~/css/mainPage1.css">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
   
    @RenderSection("CssFurkan", false)
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://unpkg.com/ionicons@4.5.10-0/dist/css/ionicons.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css">
    
    




</head>
<body>
    <div class="frame"> 
        <div class="top-items">
            @if(User.Identity.IsAuthenticated)
            {

                <a >
                    Welcome @User.Identity.Name
                    <i class="icon ion-md-person"></i>
                </a>
                <a class="login" href="/account/logout">
                    Çıkış
                    <i class="icon ion-md-person"></i>
                </a>
            }
            else
            {
                <div class="login">
                    <a href="/account/login">
                        Giriş
                        <i class="icon ion-md-person"></i>
                    </a>
                </div>
               
            }
            <div class="lang">
                <button class="langBut">Dil <i class="icon ion-md-flag"></i></button>
                <div class="dropdown">
                    <a asp-controller="navbar" asp-action="ChangeLanguage" asp-route-culture="en-US" >En</a>
                    <br>
                    <a asp-controller="navbar" asp-action="ChangeLanguage" asp-route-culture="tr-TR" >TR</a>
                </div>
            </div>
           
            
      
        </div>


     



        @*<div class="top-view">
            <span><a asp-controller="navbar" asp-action="ChangeLanguage" asp-route-culture="en-US" class="lang">En</a></span>
            <span><a asp-controller="navbar" asp-action="ChangeLanguage" asp-route-culture="tr-TR" class="lang">TR</a></span>

        </div>*@

        <partial name="_header" />
        
        <partial name="_navbar" />

        <div class="container">
        <main role="main" class="pb-3">
            @if (TempData["message"] != null)
            {
                <div class="row">
                    <div class="col-md-12">
                        <div class="alert alert-warning">
                            @TempData["message"]
                        </div>
                    </div>
                </div>
            }
            @RenderBody()
        </main>
    </div>

        
       
    @if(User.Identity.IsAuthenticated)
    {
           

            <div class="sepet">
                <a href="/cart/index">
                    <i class="icon ion-md-basket">
                    </i>
                </a>
				
			
            </div>

           
    }


        <div class="footer">
            <div class="footer-content">
                <h3>Hakkımızda</h3>
                <p>Fikir ile Gelecek / Intvice</p>
                <ul class="socials">
                    <li><a href="https://fikirilegelecek.com"><i class="fa-solid fa-link"></i></i></a></li>
                    <li><a href="https://www.facebook.com/FikirileGelecek/"><i class="fa-brands fa-facebook-f"></i></a></li>
                    <li><a href="https://twitter.com/FikirileGelecek/"><i class="fa-brands fa-twitter"></i></a></li>
                    <li><a href="https://www.instagram.com/fikirilegelecek/"><i class="fa-brands fa-instagram"></i></a></li>
                    <li><a href="https://www.youtube.com/channel/UCMEYqEyiAdOpXEtoAF5Sg1w"><i class="fa-brands fa-youtube"></i></i></a></li>
                    <li><a href="https://www.linkedin.com/company/fikirilegelecek/"><i class="fa-brands fa-linkedin"></i></i></a></li>
                </ul>
            </div>
            <div class="footer-bot">
                <p>designed by <span>Ahmet Furkan Söğütcü & Eren Bekmezci</span></p>
            </div>
        </div>
    </div> 
    <script type="module" src="~/js/index1.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="~/js/script.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

teknofest/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - teknofest</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/teknofest.styles.css" asp-append-version="true" />
   
</head>
<body>
    <header>
        
        <partial name="_navbar" />
        
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @if (TempData["message"] != null)
            {
                <div class="row">
                    <div class="col-md-12">
                        <div class="alert alert-warning">
                            @TempData["message"]
                        </div>
                    </div>
                </div>
            }
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - teknofest - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

teknofest/Views/Shared/_header.cshtml
<div class="header">
            <div class="hotel-name">
                <h1>Hotel</h1>
            </div>
            <div class="menu-title">
                <h3>&mdash; Menu &mdash;</h3>
            </div>
        </div>

teknofest/Views/Shared/_noMenu.cshtml
<div class="row">
    <div class="col-md-12">
        <div class="alert alert-danger">
            Menü yok
        </div>
    </div>
</div>